trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

# =========================
# TERRAFORM DEPLOYMENT
# =========================
- stage: Terraform
  displayName: "Terraform Infra Deployment"

  jobs:
  - job: TerraformApply
    displayName: "Create App Service Infra"

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: "Terraform Init Plan Apply"

      inputs:
        azureSubscription: 'app-hotel-coonection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |

          cd terraform

          terraform init

          terraform validate

          terraform plan

          terraform apply -auto-approve