trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'app-hotel-coonection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init
      terraform validate
      terraform plan -var-file="environments/dev/terraform.tfvars"
      terraform apply -auto-approve -var-file="environments/dev/terraform.tfvars"