variable "resource_group_name" {}
variable "location" {}
variable "app_service_plan_name" {}
variable "app_service_name" {}
variable "acr_name" {}
variable "vm_name" {}
variable "admin_username" {}
variable "admin_password" {}
variable "aks_name" {}
variable "keyvault_name" {}